name: Service Token Check and Refresh

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  check-and-refresh-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python (if scripts are in Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
            path: "./requirements.txt" # Path to your requirements file

      - name: List Tokens Expiring in Next 30 Days
        run: |
          python ./scripts/list-service-token.py
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLEVERTAP_CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_AUTHORIZATION_TOKEN: ${{ secrets.CLEVERTAP_SNE_CLOUDLFARE_AUTHORIZATION_TOKEN }}

          # Add any other required environment variables
